// GENERATED FILE -- do not edit by hand.
// Source: data/presets/districts_de.json (Stand 2026-09-23)
// Regenerate: python3 scripts/generate_districts_header.py
#pragma once
#include <stdint.h>

struct BundeslandEntry {
  const char *code;
  const char *name;
};

struct DistrictEntry {
  const char *name;
  const char *kennzeichen;
  uint8_t bundeslandIndex;
};

constexpr uint16_t kBundeslandCount = 16;
const BundeslandEntry kBundeslaender[kBundeslandCount] = {
  {"BW", "Baden-Wuerttemberg"},
  {"BY", "Bayern"},
  {"BE", "Berlin"},
  {"BB", "Brandenburg"},
  {"HB", "Bremen"},
  {"HH", "Hamburg"},
  {"HE", "Hessen"},
  {"MV", "Mecklenburg-Vorpommern"},
  {"NI", "Niedersachsen"},
  {"NW", "Nordrhein-Westfalen"},
  {"RP", "Rheinland-Pfalz"},
  {"SL", "Saarland"},
  {"SN", "Sachsen"},
  {"ST", "Sachsen-Anhalt"},
  {"SH", "Schleswig-Holstein"},
  {"TH", "Thueringen"},
};

constexpr uint16_t kDistrictCount = 401;
const DistrictEntry kDistricts[kDistrictCount] = {
  {"Barnim", "BAR", 3},
  {"Brandenburg an der Havel", "BRB", 3},
  {"Cottbus", "CB", 3},
  {"Dahme-Spreewald", "LDS", 3},
  {"Elbe-Elster", "EE", 3},
  {"Frankfurt", "FF", 3},
  {"Havelland", "HVL", 3},
  {"Maerkisch-Oderland", "MOL", 3},
  {"Oberhavel", "OHV", 3},
  {"Oberspreewald-Lausitz", "OSL", 3},
  {"Oder-Spree", "LOS", 3},
  {"Ostprignitz-Ruppin", "OPR", 3},
  {"Potsdam", "P", 3},
  {"Potsdam-Mittelmark", "PM", 3},
  {"Prignitz", "PR", 3},
  {"Spree-Neisse", "SPN", 3},
  {"Teltow-Flaeming", "TF", 3},
  {"Uckermark", "UM", 3},
  {"Berlin", "B", 2},
  {"Alb-Donau-Kreis", "UL", 0},
  {"Baden-Baden", "BAD", 0},
  {"Biberach", "BC", 0},
  {"Bodenseekreis", "FN", 0},
  {"Breisgau-Hochschwarzwald", "FR", 0},
  {"Boeblingen", "BB", 0},
  {"Calw", "CW", 0},
  {"Emmendingen", "EM", 0},
  {"Enzkreis", "PF", 0},
  {"Esslingen", "ES", 0},
  {"Freiburg im Breisgau", "FR", 0},
  {"Freudenstadt", "FDS", 0},
  {"Goeppingen", "GP", 0},
  {"Heidelberg", "HD", 0},
  {"Heidenheim", "HDH", 0},
  {"Heilbronn", "HN", 0},
  {"Heilbronn", "HN", 0},
  {"Hohenlohekreis", "KÜN", 0},
  {"Karlsruhe", "KA", 0},
  {"Karlsruhe", "KA", 0},
  {"Konstanz", "KN", 0},
  {"Ludwigsburg", "LB", 0},
  {"Loerrach", "LÖ", 0},
  {"Main-Tauber-Kreis", "TBB", 0},
  {"Mannheim", "MA", 0},
  {"Neckar-Odenwald-Kreis", "MOS", 0},
  {"Ortenaukreis", "OG", 0},
  {"Ostalbkreis", "AA", 0},
  {"Pforzheim", "PF", 0},
  {"Rastatt", "RA", 0},
  {"Ravensburg", "RV", 0},
  {"Rems-Murr-Kreis", "WN", 0},
  {"Reutlingen", "RT", 0},
  {"Rhein-Neckar-Kreis", "HD", 0},
  {"Rottweil", "RW", 0},
  {"Schwarzwald-Baar-Kreis", "VS", 0},
  {"Schwaebisch Hall", "SHA", 0},
  {"Sigmaringen", "SIG", 0},
  {"Stuttgart", "S", 0},
  {"Tuttlingen", "TUT", 0},
  {"Tuebingen", "TÜ", 0},
  {"Ulm", "UL", 0},
  {"Waldshut", "WT", 0},
  {"Zollernalbkreis", "BL", 0},
  {"Aichach-Friedberg", "AIC", 1},
  {"Altoetting", "AÖ", 1},
  {"Amberg", "AM", 1},
  {"Amberg-Sulzbach", "AS", 1},
  {"Ansbach", "AN", 1},
  {"Ansbach", "AN", 1},
  {"Aschaffenburg", "AB", 1},
  {"Aschaffenburg", "AB", 1},
  {"Augsburg", "A", 1},
  {"Augsburg", "A", 1},
  {"Bad Kissingen", "KG", 1},
  {"Bad Toelz-Wolfratshausen", "TÖL", 1},
  {"Bamberg", "BA", 1},
  {"Bamberg", "BA", 1},
  {"Bayreuth", "BT", 1},
  {"Bayreuth", "BT", 1},
  {"Berchtesgadener Land", "BGL", 1},
  {"Cham", "CHA", 1},
  {"Coburg", "CO", 1},
  {"Coburg", "CO", 1},
  {"Dachau", "DAH", 1},
  {"Deggendorf", "DEG", 1},
  {"Dillingen an der Donau", "DLG", 1},
  {"Dingolfing-Landau", "DGF", 1},
  {"Donau-Ries", "DON", 1},
  {"Ebersberg", "EBE", 1},
  {"Eichstaett", "EI", 1},
  {"Erding", "ED", 1},
  {"Erlangen", "ER", 1},
  {"Erlangen-Hoechstadt", "ERH", 1},
  {"Forchheim", "FO", 1},
  {"Freising", "FS", 1},
  {"Freyung-Grafenau", "FRG", 1},
  {"Fuerstenfeldbruck", "FFB", 1},
  {"Fuerth", "FÜ", 1},
  {"Fuerth", "FÜ", 1},
  {"Garmisch-Partenkirchen", "GAP", 1},
  {"Guenzburg", "GZ", 1},
  {"Hassberge", "HAS", 1},
  {"Hof", "HO", 1},
  {"Hof", "HO", 1},
  {"Ingolstadt", "IN", 1},
  {"Kaufbeuren", "KF", 1},
  {"Kelheim", "KEH", 1},
  {"Kempten", "KE", 1},
  {"Kitzingen", "KT", 1},
  {"Kronach", "KC", 1},
  {"Kulmbach", "KU", 1},
  {"Landsberg am Lech", "LL", 1},
  {"Landshut", "LA", 1},
  {"Landshut", "LA", 1},
  {"Lichtenfels", "LIF", 1},
  {"Lindau (Bodensee)", "LI", 1},
  {"Main-Spessart", "MSP", 1},
  {"Memmingen", "MM", 1},
  {"Miesbach", "MB", 1},
  {"Miltenberg", "MIL", 1},
  {"Muehldorf am Inn", "MÜ", 1},
  {"Muenchen", "M", 1},
  {"Muenchen", "M", 1},
  {"Neu-Ulm", "NU", 1},
  {"Neuburg-Schrobenhausen", "ND", 1},
  {"Neumarkt in der Oberpfalz", "NM", 1},
  {"Neustadt an der Aisch-Bad Windsheim", "NEA", 1},
  {"Neustadt an der Waldnaab", "NEW", 1},
  {"Nuernberg", "N", 1},
  {"Nuernberger Land", "LAU", 1},
  {"Oberallgaeu", "OA", 1},
  {"Ostallgaeu", "OAL", 1},
  {"Passau", "PA", 1},
  {"Passau", "PA", 1},
  {"Pfaffenhofen an der Ilm", "PAF", 1},
  {"Regen", "REG", 1},
  {"Regensburg", "R", 1},
  {"Regensburg", "R", 1},
  {"Rhoen-Grabfeld", "NES", 1},
  {"Rosenheim", "RO", 1},
  {"Rosenheim", "RO", 1},
  {"Roth", "RH", 1},
  {"Rottal-Inn", "PAN", 1},
  {"Schwabach", "SC", 1},
  {"Schwandorf", "SAD", 1},
  {"Schweinfurt", "SW", 1},
  {"Schweinfurt", "SW", 1},
  {"Starnberg", "STA", 1},
  {"Straubing", "SR", 1},
  {"Straubing-Bogen", "SR", 1},
  {"Tirschenreuth", "TIR", 1},
  {"Traunstein", "TS", 1},
  {"Unterallgaeu", "MN", 1},
  {"Weiden in der Oberpfalz", "WEN", 1},
  {"Weilheim-Schongau", "WM", 1},
  {"Weissenburg-Gunzenhausen", "WUG", 1},
  {"Wunsiedel im Fichtelgebirge", "WUN", 1},
  {"Wuerzburg", "WÜ", 1},
  {"Wuerzburg", "WÜ", 1},
  {"Bremen", "HB", 4},
  {"Bremerhaven", "HB", 4},
  {"Bergstrasse", "HP", 6},
  {"Darmstadt", "DA", 6},
  {"Darmstadt-Dieburg", "DA", 6},
  {"Frankfurt am Main", "F", 6},
  {"Fulda", "FD", 6},
  {"Giessen", "GI", 6},
  {"Gross-Gerau", "GG", 6},
  {"Hanau", "HU", 6},
  {"Hersfeld-Rotenburg", "HEF", 6},
  {"Hochtaunuskreis", "HG", 6},
  {"Kassel", "KS", 6},
  {"Kassel", "KS", 6},
  {"Lahn-Dill-Kreis", "LDK", 6},
  {"Limburg-Weilburg", "LM", 6},
  {"Main-Kinzig-Kreis", "MKK", 6},
  {"Main-Taunus-Kreis", "MTK", 6},
  {"Marburg-Biedenkopf", "MR", 6},
  {"Odenwaldkreis", "ERB", 6},
  {"Offenbach", "OF", 6},
  {"Offenbach am Main", "OF", 6},
  {"Rheingau-Taunus-Kreis", "RÜD", 6},
  {"Schwalm-Eder-Kreis", "HR", 6},
  {"Vogelsbergkreis", "VB", 6},
  {"Waldeck-Frankenberg", "KB", 6},
  {"Werra-Meissner-Kreis", "ESW", 6},
  {"Wetteraukreis", "FB", 6},
  {"Wiesbaden", "WI", 6},
  {"Hamburg", "HH", 5},
  {"Ludwigslust-Parchim", "LUP", 7},
  {"Mecklenburgische Seenplatte", "MSE", 7},
  {"Nordwestmecklenburg", "NWM", 7},
  {"Rostock", "LRO", 7},
  {"Rostock", "HRO", 7},
  {"Schwerin", "SN", 7},
  {"Vorpommern-Greifswald", "VG", 7},
  {"Vorpommern-Ruegen", "VR", 7},
  {"Ammerland", "WST", 8},
  {"Aurich", "AUR", 8},
  {"Braunschweig", "BS", 8},
  {"Celle", "CE", 8},
  {"Cloppenburg", "CLP", 8},
  {"Cuxhaven", "CUX", 8},
  {"Delmenhorst", "DEL", 8},
  {"Diepholz", "DH", 8},
  {"Emden", "EMD", 8},
  {"Emsland", "EL", 8},
  {"Friesland", "FRI", 8},
  {"Gifhorn", "GF", 8},
  {"Goslar", "GS", 8},
  {"Grafschaft Bentheim", "NOH", 8},
  {"Goettingen", "GÖ", 8},
  {"Hameln-Pyrmont", "HM", 8},
  {"Hannover, Region", "H", 8},
  {"Harburg", "WL", 8},
  {"Heidekreis", "HK", 8},
  {"Helmstedt", "HE", 8},
  {"Hildesheim", "HI", 8},
  {"Holzminden", "HOL", 8},
  {"Leer", "LER", 8},
  {"Luechow-Dannenberg", "DAN", 8},
  {"Lueneburg", "LG", 8},
  {"Nienburg/Weser", "NI", 8},
  {"Northeim", "NOM", 8},
  {"Oldenburg", "OL", 8},
  {"Oldenburg", "OL", 8},
  {"Osnabrueck", "OS", 8},
  {"Osnabrueck", "OS", 8},
  {"Osterholz", "OHZ", 8},
  {"Peine", "PE", 8},
  {"Rotenburg (Wuemme)", "ROW", 8},
  {"Salzgitter", "SZ", 8},
  {"Schaumburg", "SHG", 8},
  {"Stade", "STD", 8},
  {"Uelzen", "UE", 8},
  {"Vechta", "VEC", 8},
  {"Verden", "VER", 8},
  {"Wesermarsch", "BRA", 8},
  {"Wilhelmshaven", "WHV", 8},
  {"Wittmund", "WTM", 8},
  {"Wolfenbuettel", "WF", 8},
  {"Wolfsburg", "WOB", 8},
  {"Aachen, Staedteregion", "AC", 9},
  {"Bielefeld", "BI", 9},
  {"Bochum", "BO", 9},
  {"Bonn", "BN", 9},
  {"Borken", "BOR", 9},
  {"Bottrop", "BOT", 9},
  {"Coesfeld", "COE", 9},
  {"Dortmund", "DO", 9},
  {"Duisburg", "DU", 9},
  {"Dueren", "DN", 9},
  {"Duesseldorf", "D", 9},
  {"Ennepe-Ruhr-Kreis", "EN", 9},
  {"Essen", "E", 9},
  {"Euskirchen", "EU", 9},
  {"Gelsenkirchen", "GE", 9},
  {"Guetersloh", "GT", 9},
  {"Hagen", "HA", 9},
  {"Hamm", "HAM", 9},
  {"Heinsberg", "HS", 9},
  {"Herford", "HF", 9},
  {"Herne", "HER", 9},
  {"Hochsauerlandkreis", "HSK", 9},
  {"Hoexter", "HX", 9},
  {"Kleve", "KLE", 9},
  {"Krefeld", "KR", 9},
  {"Koeln", "K", 9},
  {"Leverkusen", "LEV", 9},
  {"Lippe", "LIP", 9},
  {"Mettmann", "ME", 9},
  {"Minden-Luebbecke", "MI", 9},
  {"Maerkischer Kreis", "MK", 9},
  {"Moenchengladbach", "MG", 9},
  {"Muelheim an der Ruhr", "MH", 9},
  {"Muenster", "MS", 9},
  {"Oberbergischer Kreis", "GM", 9},
  {"Oberhausen", "OB", 9},
  {"Olpe", "OE", 9},
  {"Paderborn", "PB", 9},
  {"Recklinghausen", "RE", 9},
  {"Remscheid", "RS", 9},
  {"Rhein-Erft-Kreis", "BM", 9},
  {"Rhein-Kreis Neuss", "NE", 9},
  {"Rhein-Sieg-Kreis", "SU", 9},
  {"Rheinisch-Bergischer Kreis", "GL", 9},
  {"Siegen-Wittgenstein", "SI", 9},
  {"Soest", "SO", 9},
  {"Solingen", "SG", 9},
  {"Steinfurt", "ST", 9},
  {"Unna", "UN", 9},
  {"Viersen", "VIE", 9},
  {"Warendorf", "WAF", 9},
  {"Wesel", "WES", 9},
  {"Wuppertal", "W", 9},
  {"Ahrweiler", "AW", 10},
  {"Altenkirchen (Westerwald)", "AK", 10},
  {"Alzey-Worms", "AZ", 10},
  {"Bad Duerkheim", "DÜW", 10},
  {"Bad Kreuznach", "KH", 10},
  {"Bernkastel-Wittlich", "WIL", 10},
  {"Birkenfeld", "BIR", 10},
  {"Cochem-Zell", "COC", 10},
  {"Donnersbergkreis", "KIB", 10},
  {"Eifelkreis Bitburg-Pruem", "BIT", 10},
  {"Frankenthal", "FT", 10},
  {"Germersheim", "GER", 10},
  {"Kaiserslautern", "KL", 10},
  {"Kaiserslautern", "KL", 10},
  {"Koblenz", "KO", 10},
  {"Kusel", "KUS", 10},
  {"Landau in der Pfalz", "LD", 10},
  {"Ludwigshafen am Rhein", "LU", 10},
  {"Mainz", "MZ", 10},
  {"Mainz-Bingen", "MZ", 10},
  {"Mayen-Koblenz", "MYK", 10},
  {"Neustadt an der Weinstrasse", "NW", 10},
  {"Neuwied", "NR", 10},
  {"Pirmasens", "PS", 10},
  {"Rhein-Hunsrueck-Kreis", "SIM", 10},
  {"Rhein-Lahn-Kreis", "EMS", 10},
  {"Rhein-Pfalz-Kreis", "RP", 10},
  {"Speyer", "SP", 10},
  {"Suedliche Weinstrasse", "SÜW", 10},
  {"Suedwestpfalz", "PS", 10},
  {"Trier", "TR", 10},
  {"Trier-Saarburg", "TR", 10},
  {"Vulkaneifel", "DAU", 10},
  {"Westerwaldkreis", "WW", 10},
  {"Worms", "WO", 10},
  {"Zweibruecken", "ZW", 10},
  {"Dithmarschen", "HEI", 14},
  {"Flensburg", "FL", 14},
  {"Herzogtum Lauenburg", "RZ", 14},
  {"Kiel", "KI", 14},
  {"Luebeck", "HL", 14},
  {"Neumuenster", "NMS", 14},
  {"Nordfriesland", "NF", 14},
  {"Ostholstein", "OH", 14},
  {"Pinneberg", "PI", 14},
  {"Ploen", "PLÖ", 14},
  {"Rendsburg-Eckernfoerde", "RD", 14},
  {"Schleswig-Flensburg", "SL", 14},
  {"Segeberg", "SE", 14},
  {"Steinburg", "IZ", 14},
  {"Stormarn", "OD", 14},
  {"Merzig-Wadern", "MZG", 11},
  {"Neunkirchen", "NK", 11},
  {"Saarbruecken, Regionalverband", "SB", 11},
  {"Saarlouis", "SLS", 11},
  {"Saarpfalz-Kreis", "HOM", 11},
  {"St. Wendel", "WND", 11},
  {"Bautzen", "BZ", 12},
  {"Chemnitz", "C", 12},
  {"Dresden", "DD", 12},
  {"Erzgebirgskreis", "ERZ", 12},
  {"Goerlitz", "GR", 12},
  {"Leipzig", "L", 12},
  {"Leipzig", "L", 12},
  {"Meissen", "MEI", 12},
  {"Mittelsachsen", "FG", 12},
  {"Nordsachsen", "TDO", 12},
  {"Saechsische Schweiz-Osterzgebirge", "PIR", 12},
  {"Vogtlandkreis", "V", 12},
  {"Zwickau", "Z", 12},
  {"Altmarkkreis Salzwedel", "SAW", 13},
  {"Anhalt-Bitterfeld", "ABI", 13},
  {"Burgenlandkreis", "BLK", 13},
  {"Boerde", "BK", 13},
  {"Dessau-Rosslau", "DE", 13},
  {"Halle", "HAL", 13},
  {"Harz", "HZ", 13},
  {"Jerichower Land", "JL", 13},
  {"Magdeburg", "MD", 13},
  {"Mansfeld-Suedharz", "MSH", 13},
  {"Saalekreis", "SK", 13},
  {"Salzlandkreis", "SLK", 13},
  {"Stendal", "SDL", 13},
  {"Wittenberg", "WB", 13},
  {"Altenburger Land", "ABG", 15},
  {"Eichsfeld", "EIC", 15},
  {"Erfurt", "EF", 15},
  {"Gera", "G", 15},
  {"Gotha", "GTH", 15},
  {"Greiz", "GRZ", 15},
  {"Hildburghausen", "HBN", 15},
  {"Ilm-Kreis", "IK", 15},
  {"Jena", "J", 15},
  {"Kyffhaeuserkreis", "KYF", 15},
  {"Nordhausen", "NDH", 15},
  {"Saale-Holzland-Kreis", "SHK", 15},
  {"Saale-Orla-Kreis", "SOK", 15},
  {"Saalfeld-Rudolstadt", "SLF", 15},
  {"Schmalkalden-Meiningen", "SM", 15},
  {"Sonneberg", "SON", 15},
  {"Suhl", "SHL", 15},
  {"Soemmerda", "SÖM", 15},
  {"Unstrut-Hainich-Kreis", "UH", 15},
  {"Wartburgkreis", "WAK", 15},
  {"Weimar", "WE", 15},
  {"Weimarer Land", "AP", 15},
};

